version: '3.7'

services:
  app:
    container_name: trekkstay-backend
    restart: always
    image: trekkstay-backend
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - CONFIG_PATH=./env/prod.env
      - MIGRATE=false
    ports:
      - '8888:8888'
    networks:
      - trekkstay_network

networks:
  trekkstay_network:
    name: trekkstay_network
    external: true